### PR TITLE
Add docker build & publish

### PR DESCRIPTION
**Pull request by mik3y**

### CODE REVIEW

**Comment by mik3y** [comment]
@johnnyruz please take a look!

**Review by johnnyruz — APPROVED** [review]
Looks good! I'm going to have to take your word on some of the docker buildx stuff :). Main thing I was testing is the removal of entry point from the docker-compose which I agree is automatically picked up by the container entry script.

I'll keep an eye out for the kegbot/mariadb in docker-hub and then run a test again with the master install script!

**Review by johnnyruz — APPROVED** [review]

**Review by johnnyruz — APPROVED** [review]

**Review by johnnyruz — APPROVED** [review]

**Comment by mik3y** [comment]
> Main thing I was testing is the removal of entry point from the docker-compose which I agree is automatically picked up by the container entry script.

Yep that's right! Figured since you moved it back to no arguments, may as well keep the compose file as short as possible.

Thanks for the review!

**Comment by johnnyruz** [comment]
Tested and working perfectly from a completely fresh install!

**Pull request merged**
